name: Check

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  gitleaks:
    uses: Diaszano/actions/.github/workflows/gitleaks.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  commit-check:
    uses: Diaszano/actions/.github/workflows/commit-check.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    uses: Diaszano/actions/.github/workflows/pre-commit.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
