name: Check

on:
  pull_request:


jobs:
  gitleaks:
    uses: Diaszano/actions/.github/workflows/gitleaks.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  commit-check:
    uses: Diaszano/actions/.github/workflows/commit-check.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    uses: Diaszano/actions/.github/workflows/pre-commit.yaml@main
    needs: commit-check
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
