name: Golangci-lint Formatters
description: Run golangci-lint with specific formatters to format Go code.

on:
  workflow_call:
    inputs:
      golangci-lint-version:
        description: "Version of golangci-lint to use."
        required: false
        default: "v2.7.2"
        type: string
      go-version:
        description: "Version of Go to set up."
        required: false
        default: "stable"
        type: string

jobs:
  format:
    name: Run golangci-lint with formatters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run golangci-lint with formatters
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ inputs.golangci-lint-version }}
          args: fmt
