name: Golangci-lint Formatters
description: Run golangci-lint with specific formatters to format Go code.

on:
  workflow_call:
    inputs:
      golangci-lint-version:
        description: "Version of golangci-lint to use."
        required: false
        default: "v2.7.2"
        type: string
      go-version-file:
        description: "Name of the go.mod file to use."
        required: false
        default: "go.mod"
        type: string

jobs:
  format:
    name: Run golangci-lint with formatters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - name: Run golangci-lint
        id: format
        run: |
          if [ "$(go tool -modfile=golangci-lint.mod golangci-lint fmt -d | wc -l)" -gt 0 ]; then
            echo "Golangci-lint found issues:";
            go tool -modfile=golangci-lint.mod golangci-lint fmt -d;
            exit 1;
          else
            echo "No issues found by golangci-lint.";
          fi
