name: Actions Schedule

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  gitleaks:
    uses: Diaszano/actions/.github/workflows/gitleaks.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
